apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-config
  namespace: chatbot
data:
  # Langflow is sidecar on 127.0.0.1:7860
  LANGFLOW_URL: "http://127.0.0.1:7860"
  FLOW_ID: "fcc765ae-a6ed-4f39-9c8f-d0a2ee793499"
  MONGO_DB: "stardb"
  MONGO_COLLECTION: "services"
