apiVersion: v1
kind: Secret
metadata:
  name: starai-db-secret
  namespace: starai-mongo
type: Opaque
stringData:
  MONGO_URI: "mongodb://<username>:<password>@<mongo-host>:27017/stardb?authSource=admin"
